services:
  - type: web
    name: mydash-analytics
    env: python
    plan: free
    region: ohio
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn mydash.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydash-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: mydash-db
    plan: free
    databaseName: mydash_analytics
    user: mydash_user