services:
  - type: web
    name: mydash-analytics
    env: python
    plan: free
    region: ohio
    branch: main
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn mydash.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydash-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: mydash-db
    plan: free